services:
  - type: web
    name: autonomous-bi-agent
    env: python
    pythonVersion: 3.11
    plan: free
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt --only-binary :all:
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker app:app --bind 0.0.0.0:$PORT --workers 4
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: HITL_ENABLED
        value: "true"
      - key: SMTP_USERNAME
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: SMTP_HOST
        value: sandbox.smtp.mailtrap.io
      - key: SMTP_PORT
        value: "2525"
      - key: EMAIL_FROM
        value: "test@myapp.local"
      - key: SLACK_WEBHOOK_URL
        sync: false
      - key: BI_DB_PATH
        value: /tmp/bi_agent.db
      - key: ALLOWED_ORIGINS
        value: http://localhost,http://127.0.0.1
      - key: REVENUE_SPIKE_Z
        value: "1.0"
      - key: REVENUE_SPIKE_MIN_PCT
        value: "0.0"
      - key: TREND_MIN_POINTS
        value: "3"
      - key: TREND_WINDOW
        value: "3"
      - key: SEVERITY_MED_PCT
        value: "0.15"
      - key: SEVERITY_HIGH_PCT
        value: "0.30"
      - key: USE_LLM
        value: "true"
      - key: ALERT_RECIPIENTS
        value: you@example.com,team@example.com
