services:
  - type: web
    name: autonomous-bi-agent
    env: python
    pythonVersion: 3.11
    plan: free
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker app:app --bind 0.0.0.0:$PORT --workers 4
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: HITL_ENABLED
        value: "true"
      - key: SMTP_USERNAME
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: SMTP_HOST
        value: sandbox.smtp.mailtrap.io
      - key: SMTP_PORT
        value: "2525"
      - key: EMAIL_FROM
        value: "test@myapp.local"
      - key: SLACK_WEBHOOK_URL
        sync: false

